---
name: AtulJainNodeJsWorkflow
on: 
 workflow_dispatch:
 push:
  branches:
   - master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: clone the reop
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: TESting
        run: npm test
      - name: Build the project
        run: npm run build
      - name: Deplyment of node js project
        run: echo "we will do deployment later"
